# Site settings
title:       6fingers.me
email:       hello@6fingers.me
author:      Tung D. Ta
description: >- # this means to ignore newlines until "baseurl:"
  This is a collection of my notes. Most of them are my thought after reading good research papers.
  Other articles will be how-to which are some experience that I picked-up during research, programming, and making.
baseurl:     ""
timezone: Asia/Tokyo
url:         "https://6fingers.me"
date_format: "%b %-d, %Y"
header_pages:
 - cat_opinions.md
 - cat_books.md
 - cat_howto.md
 - about.md
 - contact.html

formspree: "https://formspree.io/f/xnqoeapw"

google_analytics: UA-27976595-3
# google_tag_manager: GTM-NZHM422

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true

# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Disqus post comments
disqus_shortname: 6fingers-me

# Social icons
github_username: tatung
twitter_username: tatung2112
linkedin_username: tung-ta-duc-783aa94b

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share:'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
    post_footer:    'Lorem ipsum'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    :title
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
